AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Removes PII from data
Resources:
  lambdaremovepii:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Removes PII from data
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::474187235891:role/lambda-remove-pii-executor'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: pii
      Environment:
        Variables:
          NOPII_KEY_PREFIX: clean
          PII_KEY_PREFIX: pii
  Bucket1:
    Type: 'AWS::S3::Bucket'
